captainVersion: 4
caproverOneClickApp:
  instructions:
    start: Just a plain Docker Compose.
    end: Docker Compose is deployed.
########
version: '3'

services:
  disapp:
    image: yiisoftware/yii2-php:8.2-apache
    container_name: disapp